### ISSUE TITLE
Move to OpenShift

### ISSUE THREAD

**Issue by raucao** [67P/hal8000#1]
Heroku will cap free Dynos in 2 months. They'll have a max runtime of 18 hours per day. OpenShift is basically the same (but open source, yay) and still has a free tier for small apps.

https://www.openshift.com/

(Feel free to add other proposals/recommendations for hosting!)

**Comment by raucao** [comment]
Wow, that platform just crapped out so hard, I don't even...

Wrote to support, but we should probably look for sth different. How about we set up node.js deployments on the new Hetzner machine, @gregkare? Will need it for an always-on Sockethub instance anyway soon.

**Comment by untitaker** [comment]
If this is just about the bot, perhaps Uberspace is an option?

**Comment by raucao** [comment]
Already running at Hetzner, using Chef Solo for config management and deployments.
